In [45]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [47]:
df = pd.read_csv("/content/drive/MyDrive/archive (3).zip")
df

,Price,Property Type,Bedrooms,Bathrooms,Size,Postcode,Area,Price_Category,Area_Avg_Price
0,330000.0,Apartment,1.0,1.0,518.000000,E14,Eastern,Low,1.001684e+06
1,340000.0,Flat,1.0,1.0,887.498269,E14,Eastern,Low,1.001684e+06
2,340000.0,Apartment,1.0,1.0,934.569040,E14,Eastern,Low,1.001684e+06
3,340000.0,Flat,1.0,1.0,887.498269,E14,Eastern,Low,1.001684e+06
4,340000.0,Flat,1.0,1.0,388.000000,SW20,South Western,Low,1.516724e+06
...,...,...,...,...,...,...,...,...,...
29532,795000.0,Flat,3.0,2.0,840.000000,SW20,South Western,Medium,1.516724e+06
29533,795000.0,Flat,2.0,1.0,887.498269,E14,Eastern,Medium,1.001684e+06
29534,795000.0,Flat,2.0,2.0,753.000000,SE1,South Eastern,Medium,6.921048e+05
29535,795000.0,Flat,2.0,2.0,980.000000,SW11,South Western,Medium,1.516724e+06
29536,795000.0,Semi-Detached,3.0,1.0,2183.543103,N14,Northern,Medium,8.312952e+05

In [48]:
df.isnull().sum()

Price             0
Property Type     0
Bedrooms          0
Bathrooms         0
Size              0
Postcode          0
Area              0
Price_Category    0
Area_Avg_Price    0
dtype: int64

In [49]:
df = df.drop_duplicates()
df

,Price,Property Type,Bedrooms,Bathrooms,Size,Postcode,Area,Price_Category,Area_Avg_Price
0,330000.0,Apartment,1.0,1.0,518.000000,E14,Eastern,Low,1.001684e+06
1,340000.0,Flat,1.0,1.0,887.498269,E14,Eastern,Low,1.001684e+06
2,340000.0,Apartment,1.0,1.0,934.569040,E14,Eastern,Low,1.001684e+06
4,340000.0,Flat,1.0,1.0,388.000000,SW20,South Western,Low,1.516724e+06
5,340000.0,Apartment,2.0,1.0,230.000000,WC1N,Western Central,Low,1.625819e+06
...,...,...,...,...,...,...,...,...,...
29530,795000.0,Apartment,2.0,2.0,941.000000,SE1,South Eastern,Medium,6.921048e+05
29532,795000.0,Flat,3.0,2.0,840.000000,SW20,South Western,Medium,1.516724e+06
29534,795000.0,Flat,2.0,2.0,753.000000,SE1,South Eastern,Medium,6.921048e+05
29535,795000.0,Flat,2.0,2.0,980.000000,SW11,South Western,Medium,1.516724e+06
29536,795000.0,Semi-Detached,3.0,1.0,2183.543103,N14,Northern,Medium,8.312952e+05

In [50]:
df['Property Type'] = df['Property Type'].replace('Semi-Detached', 'Semi Detached')
df

/tmp/ipykernel_4062/3473636609.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Property Type'] = df['Property Type'].replace('Semi-Detached', 'Semi Detached')

,Price,Property Type,Bedrooms,Bathrooms,Size,Postcode,Area,Price_Category,Area_Avg_Price
0,330000.0,Apartment,1.0,1.0,518.000000,E14,Eastern,Low,1.001684e+06
1,340000.0,Flat,1.0,1.0,887.498269,E14,Eastern,Low,1.001684e+06
2,340000.0,Apartment,1.0,1.0,934.569040,E14,Eastern,Low,1.001684e+06
4,340000.0,Flat,1.0,1.0,388.000000,SW20,South Western,Low,1.516724e+06
5,340000.0,Apartment,2.0,1.0,230.000000,WC1N,Western Central,Low,1.625819e+06
...,...,...,...,...,...,...,...,...,...
29530,795000.0,Apartment,2.0,2.0,941.000000,SE1,South Eastern,Medium,6.921048e+05
29532,795000.0,Flat,3.0,2.0,840.000000,SW20,South Western,Medium,1.516724e+06
29534,795000.0,Flat,2.0,2.0,753.000000,SE1,South Eastern,Medium,6.921048e+05
29535,795000.0,Flat,2.0,2.0,980.000000,SW11,South Western,Medium,1.516724e+06
29536,795000.0,Semi Detached,3.0,1.0,2183.543103,N14,Northern,Medium,8.312952e+05

In [51]:
df = df.drop('Postcode', axis=1)
df

,Price,Property Type,Bedrooms,Bathrooms,Size,Area,Price_Category,Area_Avg_Price
0,330000.0,Apartment,1.0,1.0,518.000000,Eastern,Low,1.001684e+06
1,340000.0,Flat,1.0,1.0,887.498269,Eastern,Low,1.001684e+06
2,340000.0,Apartment,1.0,1.0,934.569040,Eastern,Low,1.001684e+06
4,340000.0,Flat,1.0,1.0,388.000000,South Western,Low,1.516724e+06
5,340000.0,Apartment,2.0,1.0,230.000000,Western Central,Low,1.625819e+06
...,...,...,...,...,...,...,...,...
29530,795000.0,Apartment,2.0,2.0,941.000000,South Eastern,Medium,6.921048e+05
29532,795000.0,Flat,3.0,2.0,840.000000,South Western,Medium,1.516724e+06
29534,795000.0,Flat,2.0,2.0,753.000000,South Eastern,Medium,6.921048e+05
29535,795000.0,Flat,2.0,2.0,980.000000,South Western,Medium,1.516724e+06
29536,795000.0,Semi Detached,3.0,1.0,2183.543103,Northern,Medium,8.312952e+05

In [52]:
df = df.drop('Area_Avg_Price', axis=1)
df

,Price,Property Type,Bedrooms,Bathrooms,Size,Area,Price_Category
0,330000.0,Apartment,1.0,1.0,518.000000,Eastern,Low
1,340000.0,Flat,1.0,1.0,887.498269,Eastern,Low
2,340000.0,Apartment,1.0,1.0,934.569040,Eastern,Low
4,340000.0,Flat,1.0,1.0,388.000000,South Western,Low
5,340000.0,Apartment,2.0,1.0,230.000000,Western Central,Low
...,...,...,...,...,...,...,...
29530,795000.0,Apartment,2.0,2.0,941.000000,South Eastern,Medium
29532,795000.0,Flat,3.0,2.0,840.000000,South Western,Medium
29534,795000.0,Flat,2.0,2.0,753.000000,South Eastern,Medium
29535,795000.0,Flat,2.0,2.0,980.000000,South Western,Medium
29536,795000.0,Semi Detached,3.0,1.0,2183.543103,Northern,Medium

In [53]:
# Example: Keep only properties under 10,000 sq ft
df =df[df['Size'] < 10000]

In [54]:
df.loc[:, 'Bedrooms'] = df['Bedrooms'].astype(int)
df.loc[:, 'Bathrooms'] = df['Bathrooms'].astype(int)

In [55]:
df.loc[:,'Size'] = df['Size'].round(2)

In [56]:
df.loc[:, 'Area'] = df['Area'].replace('Kingston', 'Kingston upon Thames')

In [57]:
print(df)

          Price  Property Type  Bedrooms  Bathrooms     Size             Area  \
0      330000.0      Apartment       1.0        1.0   518.00          Eastern
1      340000.0           Flat       1.0        1.0   887.50          Eastern
2      340000.0      Apartment       1.0        1.0   934.57          Eastern
4      340000.0           Flat       1.0        1.0   388.00    South Western
5      340000.0      Apartment       2.0        1.0   230.00  Western Central
...         ...            ...       ...        ...      ...              ...
29530  795000.0      Apartment       2.0        2.0   941.00    South Eastern
29532  795000.0           Flat       3.0        2.0   840.00    South Western
29534  795000.0           Flat       2.0        2.0   753.00    South Eastern
29535  795000.0           Flat       2.0        2.0   980.00    South Western
29536  795000.0  Semi Detached       3.0        1.0  2183.54         Northern

      Price_Category
0                Low
1                Low
2                Low
4                Low
5                Low
...              ...
29530         Medium
29532         Medium
29534         Medium
29535         Medium
29536         Medium

[23778 rows x 7 columns]

In [58]:
df =df[df['Bedrooms'] < 13]
df

,Price,Property Type,Bedrooms,Bathrooms,Size,Area,Price_Category
0,330000.0,Apartment,1.0,1.0,518.00,Eastern,Low
1,340000.0,Flat,1.0,1.0,887.50,Eastern,Low
2,340000.0,Apartment,1.0,1.0,934.57,Eastern,Low
4,340000.0,Flat,1.0,1.0,388.00,South Western,Low
5,340000.0,Apartment,2.0,1.0,230.00,Western Central,Low
...,...,...,...,...,...,...,...
29530,795000.0,Apartment,2.0,2.0,941.00,South Eastern,Medium
29532,795000.0,Flat,3.0,2.0,840.00,South Western,Medium
29534,795000.0,Flat,2.0,2.0,753.00,South Eastern,Medium
29535,795000.0,Flat,2.0,2.0,980.00,South Western,Medium
29536,795000.0,Semi Detached,3.0,1.0,2183.54,Northern,Medium

In [59]:
df = pd.get_dummies(
    df,
    columns=['Area', 'Property Type', 'Price_Category'],
    dtype=int
)

In [60]:
df

,Price,Bedrooms,Bathrooms,Size,Area_Bromley,Area_Croydon,Area_Eastern,Area_Eastern Central,Area_Enfield,Area_Harrow,...,Area_Western and Paddington,Property Type_Apartment,Property Type_Flat,Property Type_House,Property Type_Semi Detached,Property Type_Terraced,Price_Category_High,Price_Category_Low,Price_Category_Luxury,Price_Category_Medium
0,330000.0,1.0,1.0,518.00,0,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1,340000.0,1.0,1.0,887.50,0,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,340000.0,1.0,1.0,934.57,0,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
4,340000.0,1.0,1.0,388.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
5,340000.0,2.0,1.0,230.00,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29530,795000.0,2.0,2.0,941.00,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
29532,795000.0,3.0,2.0,840.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
29534,795000.0,2.0,2.0,753.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
29535,795000.0,2.0,2.0,980.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
29536,795000.0,3.0,1.0,2183.54,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1

In [61]:
df_encoded = df.copy() # Preserve the DataFrame with original columns after one-hot encoding
scaler = MinMaxScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df_encoded), columns=df_encoded.columns)

In [62]:
df

,Price,Bedrooms,Bathrooms,Size,Area_Bromley,Area_Croydon,Area_Eastern,Area_Eastern Central,Area_Enfield,Area_Harrow,...,Area_Western and Paddington,Property Type_Apartment,Property Type_Flat,Property Type_House,Property Type_Semi Detached,Property Type_Terraced,Price_Category_High,Price_Category_Low,Price_Category_Luxury,Price_Category_Medium
0,330000.0,1.0,1.0,518.00,0,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1,340000.0,1.0,1.0,887.50,0,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,340000.0,1.0,1.0,934.57,0,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
4,340000.0,1.0,1.0,388.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
5,340000.0,2.0,1.0,230.00,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29530,795000.0,2.0,2.0,941.00,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
29532,795000.0,3.0,2.0,840.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
29534,795000.0,2.0,2.0,753.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
29535,795000.0,2.0,2.0,980.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
29536,795000.0,3.0,1.0,2183.54,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1

In [63]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# 1. Split your data
X = df_scaled.drop('Price', axis=1)
y = df_scaled['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

# 1. Initialize and Train the Model
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# 2. Make Predictions
y_train_pred = lr_model.predict(X_train)
y_test_pred = lr_model.predict(X_test)

# 3. Calculate Accuracy
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

print(f"--- Linear Regression Results ---")
print(f"Training R2: {train_r2:.4f}")
print(f"Testing R2: {test_r2:.4f}")
print(f"Difference (Gap): {abs(train_r2 - test_r2):.4f}")

--- Linear Regression Results ---
Training R2: 0.8591
Testing R2: 0.8609
Difference (Gap): 0.0018

In [64]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [65]:
MAE = mean_absolute_error(y_test, y_test_pred)
MSE = mean_squared_error(y_test, y_test_pred)
RMSE = np.sqrt(MSE)
print(f"MAE:{MAE:.2f}")
print(f"MSE:{MSE:.2f}")
print(f"RMSE:{RMSE:.2f}")

MAE:0.03
MSE:0.00
RMSE:0.06